data:
  data_root_path: datasets
  dataset_name: CAT
  img_size: 256

model:
  batch_size: 8
  ddpm:
    type: "simple"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True
    initial_checkpoint: "ckpt/CAT.ckpt"

dm:
  schedule_name: linear
  num_diffusion_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

workers: 8
seed: 1000
log_freq: 1