data:
  data_root_path: datasets
  dataset_name: CIFAR10
  img_size: 32

model:
  batch_size: 8
  ddpm:
    type: "simple"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 2, 2]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.1
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True
    initial_checkpoint: "ckpt/CIFAR10.ckpt"

dm:
  schedule_name: linear
  num_diffusion_timesteps: 1000
  skip_type: "quad"
  beta_start: 0.0001
  beta_end: 0.02

workers: 8
seed: 1000
log_freq: 1